export const quotes = [
    "What the heck is a furniture?!!",
    "ur looking cute today",
    "meow",
    "personally i think the governments should give catgirls money",
    "awa",
    "there is no war in ba sing sei",
    "catgirls holding hands :shyfingies:",
    "i should become a language nerd so i can make a language entirely composed of meows for catgirls",
    "why cant it just be as easy as catgirl go meowmeow",
    "god knew i would be too powerful so he made me a shy catgirl with attachment issues",
    "have you seen the twitch ceo doing an interview in vrchat as gandalf the white surrounded by catgirls",
    "world cold and dark, tibbies soft and warm",
    "you should beat me up",
    "u should put meeee in a box and ship me somewhere random",
    "Only a spoonfulllllllllll",
    "it should be illegal to force a sleepy girl to wake up and go outside",
    "..cute girls love the blahaj",
    "give me 500 yen",
    "heckin say gex",
    "where'd you get such a long bacon? long bacon store",
    "DO NOT BECOME FRIENDS WITH COMPUTER SCIENCE MAJORS!!!!! THEY are annoying",
    "don't care didn't ask plus im wagging my tail going arf arf wraff bark",
    "<- tired after a long day of being gay",
    "hostage or not sometimes it's nice being held :3",
    "they don't know im a puppy",
    "good girl",
    "i hardly know er!",
    "you are valid",
    "i think i may be transgender",
    "Cargo space? No, car go road",
    "blahaj, Doo Doo Doo Doo Doo Doo",
    "i hope you smile today",
    "seas the day with a smile",
    "keep calm and swim on!",
    "hug a blåhaj, now! i am not asking.",
    "this shark is cute, but not as cute as you!",
    "make a wish upon this shark",
    "you can do it! make your dreams come true!",
    "you're a wonderful person",
    "get snuggled!",
]